/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/appart.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Office(props) {
  const { nodes, materials } = useGLTF('./models/appart.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-4.473, 6.662, -5.917]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials['Matériau.017']} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Matériau.018']} />
        <mesh geometry={nodes.Cube032_3.geometry} material={materials['Matériau.041']} />
        <mesh geometry={nodes.Cube032_4.geometry} material={materials.UberTexture} />
        <mesh geometry={nodes.Cube032_5.geometry} material={materials['Matériau.011']} />
        <mesh geometry={nodes.Cube032_6.geometry} material={nodes.Cube032_6.material} />
        <mesh geometry={nodes.Cube032_7.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube032_8.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube032_9.geometry} material={materials.unnamed} />
        <mesh geometry={nodes.Cube032_10.geometry} material={materials['Matériau.027']} />
        <mesh geometry={nodes.Cube032_11.geometry} material={materials['Matériau.026']} />
        <mesh geometry={nodes.Cube032_12.geometry} material={materials['Matériau.024']} />
        <mesh geometry={nodes.Cube032_13.geometry} material={materials['Matériau.007']} />
        <mesh geometry={nodes.Cube032_14.geometry} material={materials['Matériau.022']} />
        <mesh geometry={nodes.Cube032_15.geometry} material={materials['Matériau.023']} />
        <mesh geometry={nodes.Cube032_16.geometry} material={materials['Matériau.021']} />
        <mesh geometry={nodes.Cube032_17.geometry} material={materials['Matériau.032']} />
        <mesh geometry={nodes.Cube032_18.geometry} material={materials['Matériau.033']} />
        <mesh geometry={nodes.Cube032_19.geometry} material={materials['Matériau.031']} />
        <mesh geometry={nodes.Cube032_20.geometry} material={materials['Matériau.008']} />
      </group>
      <group position={[-0.106, 3.865, -6.469]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Matériau.040']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Matériau.016']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials.PC_Glass} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials['Matériau.013']} />
        <mesh geometry={nodes.Cube006_5.geometry} material={materials['Matériau.012']} />
        <mesh geometry={nodes.Cube006_6.geometry} material={nodes.Cube006_6.material} />
        <mesh geometry={nodes.Cube006_7.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube006_8.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube006_9.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube006_10.geometry} material={materials['Matériau.015']} />
        <mesh geometry={nodes.Cube006_11.geometry} material={materials['Matériau.014']} />
        <mesh geometry={nodes.Cube006_12.geometry} material={materials['Matériau.047']} />
        <mesh geometry={nodes.Cube006_13.geometry} material={materials['Matériau.042']} />
        <mesh geometry={nodes.Cube006_14.geometry} material={materials['Matériau.043']} />
        <mesh geometry={nodes.Cube006_15.geometry} material={materials['Matériau.045']} />
        <mesh geometry={nodes.Cube006_16.geometry} material={materials['Matériau.044']} />
        <mesh geometry={nodes.Cube006_17.geometry} material={materials['Matériau.046']} />
        <mesh geometry={nodes.Cube006_18.geometry} material={materials['Matériau.032']} />
        <mesh geometry={nodes.Cube006_19.geometry} material={materials['Matériau.030']} />
        <mesh geometry={nodes.Cube006_20.geometry} material={materials['Matériau.028']} />
        <mesh geometry={nodes.Cube006_21.geometry} material={materials['Matériau.029']} />
      </group>
      <group position={[-1.053, -0.853, -1.383]}>
        <mesh geometry={nodes.Cube047.geometry} material={materials['Matériau.025']} />
        <mesh geometry={nodes.Cube047_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube047_2.geometry} material={materials['Matériau.003']} />
        <mesh geometry={nodes.Cube047_3.geometry} material={materials['Matériau.002']} />
        <mesh geometry={nodes.Cube047_4.geometry} material={materials['Matériau.006']} />
        <mesh geometry={nodes.Cube047_5.geometry} material={materials.tapie} />
        <mesh geometry={nodes.Cube047_6.geometry} material={materials.PC_Glass} />
        <mesh geometry={nodes.Cube047_7.geometry} material={materials['Matériau.004']} />
        <mesh geometry={nodes.Cube047_8.geometry} material={materials['Matériau.005']} />
        <mesh geometry={nodes.Cube047_9.geometry} material={materials['Matériau.001']} />
        <mesh geometry={nodes.Cube047_10.geometry} material={materials['Matériau.007']} />
        <mesh geometry={nodes.Cube047_11.geometry} material={materials['Matériau.010']} />
        <mesh geometry={nodes.Cube047_12.geometry} material={materials['Matériau.019']} />
        <mesh geometry={nodes.Cube047_13.geometry} material={materials['Matériau.008']} />
        <mesh geometry={nodes.Cube047_14.geometry} material={nodes.Cube047_14.material} />
        <mesh geometry={nodes.Cube047_15.geometry} material={materials['Matériau.009']} />
        <mesh geometry={nodes.Cube047_16.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube047_17.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube047_18.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube047_19.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube047_20.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube047_21.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube047_22.geometry} material={materials['Matériau.020']} />
        <mesh geometry={nodes.Cube047_23.geometry} material={materials['Matériau.022']} />
        <mesh geometry={nodes.Cube047_24.geometry} material={materials['Matériau.023']} />
        <mesh geometry={nodes.Cube047_25.geometry} material={materials['Matériau.021']} />
        <mesh geometry={nodes.Cube047_26.geometry} material={materials['Matériau.027']} />
        <mesh geometry={nodes.Cube047_27.geometry} material={materials['Matériau.026']} />
        <mesh geometry={nodes.Cube047_28.geometry} material={materials['Matériau.024']} />
        <mesh geometry={nodes.Cube047_29.geometry} material={materials['Matériau.030']} />
        <mesh geometry={nodes.Cube047_30.geometry} material={materials['Matériau.029']} />
        <mesh geometry={nodes.Cube047_31.geometry} material={materials['Matériau.028']} />
        <mesh geometry={nodes.Cube047_32.geometry} material={materials['Matériau.032']} />
        <mesh geometry={nodes.Cube047_33.geometry} material={materials['Matériau.033']} />
        <mesh geometry={nodes.Cube047_34.geometry} material={materials['Matériau.031']} />
        <mesh geometry={nodes.Cube047_35.geometry} material={materials['Matériau.039']} />
        <mesh geometry={nodes.Cube047_36.geometry} material={materials['Matériau.038']} />
        <mesh geometry={nodes.Cube047_37.geometry} material={materials['Matériau.037']} />
        <mesh geometry={nodes.Cube047_38.geometry} material={materials['Matériau.036']} />
        <mesh geometry={nodes.Cube047_39.geometry} material={materials['Matériau.035']} />
        <mesh geometry={nodes.Cube047_40.geometry} material={materials['Matériau.034']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/appart.glb')
